### ISSUE TITLE
Nothing display!

### ISSUE THREAD

**Issue by lovebdsobuj** [JustTrust/WeatherToday#1]
If I open **`WeatherToday`** application from Notification list, nothing display!

**Comment by JustTrust** [comment]
Please tell name of your device and Android version and I will try to fix it.

**Comment by lovebdsobuj** [comment]
# Nox Android Player

Android 4.4.2 (19) KITKAT

**Comment by JustTrust** [comment]
Ok, thanks. I will run application on the Nox Android Player and we will see what happen.

**Comment by lovebdsobuj** [comment]
Okay...

**Comment by JustTrust** [comment]
I fixed it. Please check and let me know.
